// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_user_layout from "./routes/[user]/_layout.tsx";
import * as $_user_middleware from "./routes/[user]/_middleware.ts";
import * as $_user_edit from "./routes/[user]/edit.tsx";
import * as $_user_index from "./routes/[user]/index.tsx";
import * as $_user_manage from "./routes/[user]/manage.tsx";
import * as $_user_partial_edit from "./routes/[user]/partial/edit.tsx";
import * as $_user_partial_manage from "./routes/[user]/partial/manage.tsx";
import * as $_user_partial_view from "./routes/[user]/partial/view.tsx";
import * as $_user_view from "./routes/[user]/view.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about_index from "./routes/about/index.tsx";
import * as $account_layout from "./routes/account/_layout.tsx";
import * as $account_forgotpassword from "./routes/account/forgotpassword.tsx";
import * as $account_login from "./routes/account/login.tsx";
import * as $account_partials_forgotpassword from "./routes/account/partials/forgotpassword.tsx";
import * as $account_partials_login from "./routes/account/partials/login.tsx";
import * as $account_partials_register from "./routes/account/partials/register.tsx";
import * as $account_register from "./routes/account/register.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_auth_session from "./routes/api/auth/session.ts";
import * as $api_auth_switchUser from "./routes/api/auth/switchUser.ts";
import * as $api_chats_id_index from "./routes/api/chats/[id]/index.ts";
import * as $api_chats_id_messages from "./routes/api/chats/[id]/messages.ts";
import * as $api_chats_id_subscribe from "./routes/api/chats/[id]/subscribe.ts";
import * as $api_chats_index from "./routes/api/chats/index.ts";
import * as $api_files_id_ from "./routes/api/files/[id].ts";
import * as $api_files_index from "./routes/api/files/index.ts";
import * as $api_files_process_image_proxy from "./routes/api/files/process/image/proxy.ts";
import * as $api_files_process_image_resize from "./routes/api/files/process/image/resize.ts";
import * as $api_projects_id_newRole from "./routes/api/projects/[id]/newRole.ts";
import * as $api_projects_index from "./routes/api/projects/index.ts";
import * as $api_projects_newProject from "./routes/api/projects/newProject.ts";
import * as $api_teams_id_index from "./routes/api/teams/[id]/index.ts";
import * as $api_teams_id_login from "./routes/api/teams/[id]/login.ts";
import * as $api_teams_index from "./routes/api/teams/index.ts";
import * as $api_teams_logged from "./routes/api/teams/logged.ts";
import * as $api_teams_logout from "./routes/api/teams/logout.ts";
import * as $api_test from "./routes/api/test.ts";
import * as $api_user_id_ from "./routes/api/user/[id].ts";
import * as $api_user_index from "./routes/api/user/index.ts";
import * as $api_user_projects_id_chats from "./routes/api/user/projects/[id]/chats.ts";
import * as $api_user_projects_id_index from "./routes/api/user/projects/[id]/index.ts";
import * as $api_user_projects_index from "./routes/api/user/projects/index.ts";
import * as $dashboard_index from "./routes/dashboard/index.tsx";
import * as $explore_layout from "./routes/explore/_layout.tsx";
import * as $explore_index from "./routes/explore/index.tsx";
import * as $explore_partials_projects_index from "./routes/explore/partials/projects/index.tsx";
import * as $explore_people_index from "./routes/explore/people/index.tsx";
import * as $explore_posts_index from "./routes/explore/posts/index.tsx";
import * as $explore_projects_index from "./routes/explore/projects/index.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $messages_chatid_attachments_attId_ from "./routes/messages/[chatid]/attachments/[attId].tsx";
import * as $messages_chatid_attachments_index from "./routes/messages/[chatid]/attachments/index.tsx";
import * as $messages_chatid_chat from "./routes/messages/[chatid]/chat.tsx";
import * as $messages_chatid_info from "./routes/messages/[chatid]/info.tsx";
import * as $messages_chatid_partials_attachments_attId_ from "./routes/messages/[chatid]/partials/attachments/[attId].tsx";
import * as $messages_chatid_partials_attachments_index from "./routes/messages/[chatid]/partials/attachments/index.tsx";
import * as $messages_chatid_partials_chat from "./routes/messages/[chatid]/partials/chat.tsx";
import * as $messages_chatid_partials_info from "./routes/messages/[chatid]/partials/info.tsx";
import * as $messages_layout from "./routes/messages/_layout.tsx";
import * as $messages_index from "./routes/messages/index.tsx";
import * as $projects_project_chatid_attachments_attId_ from "./routes/projects/[project]/[chatid]/attachments/[attId].tsx";
import * as $projects_project_chatid_attachments_index from "./routes/projects/[project]/[chatid]/attachments/index.tsx";
import * as $projects_project_chatid_chat from "./routes/projects/[project]/[chatid]/chat.tsx";
import * as $projects_project_chatid_description from "./routes/projects/[project]/[chatid]/description.tsx";
import * as $projects_project_chatid_info from "./routes/projects/[project]/[chatid]/info.tsx";
import * as $projects_project_chatid_partials_attachments_attId_ from "./routes/projects/[project]/[chatid]/partials/attachments/[attId].tsx";
import * as $projects_project_chatid_partials_attachments_index from "./routes/projects/[project]/[chatid]/partials/attachments/index.tsx";
import * as $projects_project_chatid_partials_chat from "./routes/projects/[project]/[chatid]/partials/chat.tsx";
import * as $projects_project_chatid_partials_description from "./routes/projects/[project]/[chatid]/partials/description.tsx";
import * as $projects_project_chatid_partials_info from "./routes/projects/[project]/[chatid]/partials/info.tsx";
import * as $projects_project_chatid_partials_submissions from "./routes/projects/[project]/[chatid]/partials/submissions.tsx";
import * as $projects_project_chatid_submissions from "./routes/projects/[project]/[chatid]/submissions.tsx";
import * as $projects_project_description from "./routes/projects/[project]/description.tsx";
import * as $projects_project_index from "./routes/projects/[project]/index.tsx";
import * as $projects_project_timeline from "./routes/projects/[project]/timeline.tsx";
import * as $projects_layout from "./routes/projects/_layout.tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $projects_newProject from "./routes/projects/newProject.tsx";
import * as $projects_partials_project_description from "./routes/projects/partials/[project]/description.tsx";
import * as $projects_partials_project_index from "./routes/projects/partials/[project]/index.tsx";
import * as $projects_partials_project_timeline from "./routes/projects/partials/[project]/timeline.tsx";
import * as $projects_partials_index from "./routes/projects/partials/index.tsx";
import * as $projects_partials_newProject from "./routes/projects/partials/newProject.tsx";
import * as $teams_layout from "./routes/teams/_layout.tsx";
import * as $teams_index from "./routes/teams/index.tsx";
import * as $teams_newTeam from "./routes/teams/newTeam.tsx";
import * as $teams_partials_index from "./routes/teams/partials/index.tsx";
import * as $teams_partials_newTeam from "./routes/teams/partials/newTeam.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Edit_EditImages from "./islands/Edit/EditImages.tsx";
import * as $Edit_EditLayout from "./islands/Edit/EditLayout.tsx";
import * as $Edit_EditSideNav from "./islands/Edit/EditSideNav.tsx";
import * as $Edit_EditTools from "./islands/Edit/EditTools.tsx";
import * as $Edit_forms_profile from "./islands/Edit/forms/profile.tsx";
import * as $Edit_forms_projects_budget from "./islands/Edit/forms/projects/budget.tsx";
import * as $Edit_forms_projects_job from "./islands/Edit/forms/projects/job.tsx";
import * as $Edit_forms_projects_projects from "./islands/Edit/forms/projects/projects.tsx";
import * as $Edit_forms_projects_timeline from "./islands/Edit/forms/projects/timeline.tsx";
import * as $Edit_forms_team from "./islands/Edit/forms/team.tsx";
import * as $ExploreFilter from "./islands/ExploreFilter.tsx";
import * as $Navbar_GuestNav from "./islands/Navbar/GuestNav.tsx";
import * as $Navbar_Navbar from "./islands/Navbar/Navbar.tsx";
import * as $Navbar_SideNav from "./islands/Navbar/SideNav.tsx";
import * as $Navbar_UserNav from "./islands/Navbar/UserNav.tsx";
import * as $Navbar_profileModal_Profile from "./islands/Navbar/profileModal/Profile.tsx";
import * as $Navbar_profileModal_ProfileModal from "./islands/Navbar/profileModal/ProfileModal.tsx";
import * as $Navbar_profileModal_Profiles from "./islands/Navbar/profileModal/Profiles.tsx";
import * as $Navbar_profileModal_UserNav from "./islands/Navbar/profileModal/UserNav.tsx";
import * as $Navbar_profileModal_UserSwitch from "./islands/Navbar/profileModal/UserSwitch.tsx";
import * as $Navbar_utils from "./islands/Navbar/utils.ts";
import * as $Teams_NewTeam from "./islands/Teams/NewTeam.tsx";
import * as $Teams_Teams from "./islands/Teams/Teams.tsx";
import * as $Test from "./islands/Test.tsx";
import * as $Textbox from "./islands/Textbox.tsx";
import * as $account_Login from "./islands/account/Login.tsx";
import * as $account_Register from "./islands/account/Register.tsx";
import * as $chat_ChatLayout from "./islands/chat/ChatLayout.tsx";
import * as $chat_ChatResize from "./islands/chat/ChatResize.tsx";
import * as $chat_ChatsList from "./islands/chat/ChatsList.tsx";
import * as $chat_attachments_Attachment from "./islands/chat/attachments/Attachment.tsx";
import * as $chat_attachments_Attachments from "./islands/chat/attachments/Attachments.tsx";
import * as $chat_attachments_FileList from "./islands/chat/attachments/FileList.tsx";
import * as $chat_attachments_PreviewFile from "./islands/chat/attachments/PreviewFile.tsx";
import * as $chat_messages_ChatMessage from "./islands/chat/messages/ChatMessage.tsx";
import * as $chat_messages_ChatMessages from "./islands/chat/messages/ChatMessages.tsx";
import * as $chat_messages_ChatSection from "./islands/chat/messages/ChatSection.tsx";
import * as $contexts_KVProvider from "./islands/contexts/KVProvider.tsx";
import * as $contexts_UserProvider from "./islands/contexts/UserProvider.tsx";
import * as $explore_ExploreFilter from "./islands/explore/ExploreFilter.tsx";
import * as $explore_ProjectDetails from "./islands/explore/ProjectDetails.tsx";
import * as $explore_Projects_ExploreProjects from "./islands/explore/Projects/ExploreProjects.tsx";
import * as $explore_Projects_ExploreProjectsDetails from "./islands/explore/Projects/ExploreProjectsDetails.tsx";
import * as $explore_Projects_ExploreProjectsList from "./islands/explore/Projects/ExploreProjectsList.tsx";
import * as $profile_edit from "./islands/profile/edit.tsx";
import * as $profile_layout from "./islands/profile/layout.tsx";
import * as $profile_profile from "./islands/profile/profile.tsx";
import * as $projects_NewProject from "./islands/projects/NewProject.tsx";
import * as $projects_ProjectChatList from "./islands/projects/ProjectChatList.tsx";
import * as $projects_ProjectMessages from "./islands/projects/ProjectMessages.tsx";
import * as $projects_ProjectsHeader from "./islands/projects/ProjectsHeader.tsx";
import * as $projects_ProjectsLayout from "./islands/projects/ProjectsLayout.tsx";
import * as $projects_ProjectsList from "./islands/projects/ProjectsList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[user]/_layout.tsx": $_user_layout,
    "./routes/[user]/_middleware.ts": $_user_middleware,
    "./routes/[user]/edit.tsx": $_user_edit,
    "./routes/[user]/index.tsx": $_user_index,
    "./routes/[user]/manage.tsx": $_user_manage,
    "./routes/[user]/partial/edit.tsx": $_user_partial_edit,
    "./routes/[user]/partial/manage.tsx": $_user_partial_manage,
    "./routes/[user]/partial/view.tsx": $_user_partial_view,
    "./routes/[user]/view.tsx": $_user_view,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about/index.tsx": $about_index,
    "./routes/account/_layout.tsx": $account_layout,
    "./routes/account/forgotpassword.tsx": $account_forgotpassword,
    "./routes/account/login.tsx": $account_login,
    "./routes/account/partials/forgotpassword.tsx":
      $account_partials_forgotpassword,
    "./routes/account/partials/login.tsx": $account_partials_login,
    "./routes/account/partials/register.tsx": $account_partials_register,
    "./routes/account/register.tsx": $account_register,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/auth/session.ts": $api_auth_session,
    "./routes/api/auth/switchUser.ts": $api_auth_switchUser,
    "./routes/api/chats/[id]/index.ts": $api_chats_id_index,
    "./routes/api/chats/[id]/messages.ts": $api_chats_id_messages,
    "./routes/api/chats/[id]/subscribe.ts": $api_chats_id_subscribe,
    "./routes/api/chats/index.ts": $api_chats_index,
    "./routes/api/files/[id].ts": $api_files_id_,
    "./routes/api/files/index.ts": $api_files_index,
    "./routes/api/files/process/image/proxy.ts": $api_files_process_image_proxy,
    "./routes/api/files/process/image/resize.ts":
      $api_files_process_image_resize,
    "./routes/api/projects/[id]/newRole.ts": $api_projects_id_newRole,
    "./routes/api/projects/index.ts": $api_projects_index,
    "./routes/api/projects/newProject.ts": $api_projects_newProject,
    "./routes/api/teams/[id]/index.ts": $api_teams_id_index,
    "./routes/api/teams/[id]/login.ts": $api_teams_id_login,
    "./routes/api/teams/index.ts": $api_teams_index,
    "./routes/api/teams/logged.ts": $api_teams_logged,
    "./routes/api/teams/logout.ts": $api_teams_logout,
    "./routes/api/test.ts": $api_test,
    "./routes/api/user/[id].ts": $api_user_id_,
    "./routes/api/user/index.ts": $api_user_index,
    "./routes/api/user/projects/[id]/chats.ts": $api_user_projects_id_chats,
    "./routes/api/user/projects/[id]/index.ts": $api_user_projects_id_index,
    "./routes/api/user/projects/index.ts": $api_user_projects_index,
    "./routes/dashboard/index.tsx": $dashboard_index,
    "./routes/explore/_layout.tsx": $explore_layout,
    "./routes/explore/index.tsx": $explore_index,
    "./routes/explore/partials/projects/index.tsx":
      $explore_partials_projects_index,
    "./routes/explore/people/index.tsx": $explore_people_index,
    "./routes/explore/posts/index.tsx": $explore_posts_index,
    "./routes/explore/projects/index.tsx": $explore_projects_index,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/messages/[chatid]/attachments/[attId].tsx":
      $messages_chatid_attachments_attId_,
    "./routes/messages/[chatid]/attachments/index.tsx":
      $messages_chatid_attachments_index,
    "./routes/messages/[chatid]/chat.tsx": $messages_chatid_chat,
    "./routes/messages/[chatid]/info.tsx": $messages_chatid_info,
    "./routes/messages/[chatid]/partials/attachments/[attId].tsx":
      $messages_chatid_partials_attachments_attId_,
    "./routes/messages/[chatid]/partials/attachments/index.tsx":
      $messages_chatid_partials_attachments_index,
    "./routes/messages/[chatid]/partials/chat.tsx":
      $messages_chatid_partials_chat,
    "./routes/messages/[chatid]/partials/info.tsx":
      $messages_chatid_partials_info,
    "./routes/messages/_layout.tsx": $messages_layout,
    "./routes/messages/index.tsx": $messages_index,
    "./routes/projects/[project]/[chatid]/attachments/[attId].tsx":
      $projects_project_chatid_attachments_attId_,
    "./routes/projects/[project]/[chatid]/attachments/index.tsx":
      $projects_project_chatid_attachments_index,
    "./routes/projects/[project]/[chatid]/chat.tsx":
      $projects_project_chatid_chat,
    "./routes/projects/[project]/[chatid]/description.tsx":
      $projects_project_chatid_description,
    "./routes/projects/[project]/[chatid]/info.tsx":
      $projects_project_chatid_info,
    "./routes/projects/[project]/[chatid]/partials/attachments/[attId].tsx":
      $projects_project_chatid_partials_attachments_attId_,
    "./routes/projects/[project]/[chatid]/partials/attachments/index.tsx":
      $projects_project_chatid_partials_attachments_index,
    "./routes/projects/[project]/[chatid]/partials/chat.tsx":
      $projects_project_chatid_partials_chat,
    "./routes/projects/[project]/[chatid]/partials/description.tsx":
      $projects_project_chatid_partials_description,
    "./routes/projects/[project]/[chatid]/partials/info.tsx":
      $projects_project_chatid_partials_info,
    "./routes/projects/[project]/[chatid]/partials/submissions.tsx":
      $projects_project_chatid_partials_submissions,
    "./routes/projects/[project]/[chatid]/submissions.tsx":
      $projects_project_chatid_submissions,
    "./routes/projects/[project]/description.tsx":
      $projects_project_description,
    "./routes/projects/[project]/index.tsx": $projects_project_index,
    "./routes/projects/[project]/timeline.tsx": $projects_project_timeline,
    "./routes/projects/_layout.tsx": $projects_layout,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/projects/newProject.tsx": $projects_newProject,
    "./routes/projects/partials/[project]/description.tsx":
      $projects_partials_project_description,
    "./routes/projects/partials/[project]/index.tsx":
      $projects_partials_project_index,
    "./routes/projects/partials/[project]/timeline.tsx":
      $projects_partials_project_timeline,
    "./routes/projects/partials/index.tsx": $projects_partials_index,
    "./routes/projects/partials/newProject.tsx": $projects_partials_newProject,
    "./routes/teams/_layout.tsx": $teams_layout,
    "./routes/teams/index.tsx": $teams_index,
    "./routes/teams/newTeam.tsx": $teams_newTeam,
    "./routes/teams/partials/index.tsx": $teams_partials_index,
    "./routes/teams/partials/newTeam.tsx": $teams_partials_newTeam,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Edit/EditImages.tsx": $Edit_EditImages,
    "./islands/Edit/EditLayout.tsx": $Edit_EditLayout,
    "./islands/Edit/EditSideNav.tsx": $Edit_EditSideNav,
    "./islands/Edit/EditTools.tsx": $Edit_EditTools,
    "./islands/Edit/forms/profile.tsx": $Edit_forms_profile,
    "./islands/Edit/forms/projects/budget.tsx": $Edit_forms_projects_budget,
    "./islands/Edit/forms/projects/job.tsx": $Edit_forms_projects_job,
    "./islands/Edit/forms/projects/projects.tsx": $Edit_forms_projects_projects,
    "./islands/Edit/forms/projects/timeline.tsx": $Edit_forms_projects_timeline,
    "./islands/Edit/forms/team.tsx": $Edit_forms_team,
    "./islands/ExploreFilter.tsx": $ExploreFilter,
    "./islands/Navbar/GuestNav.tsx": $Navbar_GuestNav,
    "./islands/Navbar/Navbar.tsx": $Navbar_Navbar,
    "./islands/Navbar/SideNav.tsx": $Navbar_SideNav,
    "./islands/Navbar/UserNav.tsx": $Navbar_UserNav,
    "./islands/Navbar/profileModal/Profile.tsx": $Navbar_profileModal_Profile,
    "./islands/Navbar/profileModal/ProfileModal.tsx":
      $Navbar_profileModal_ProfileModal,
    "./islands/Navbar/profileModal/Profiles.tsx": $Navbar_profileModal_Profiles,
    "./islands/Navbar/profileModal/UserNav.tsx": $Navbar_profileModal_UserNav,
    "./islands/Navbar/profileModal/UserSwitch.tsx":
      $Navbar_profileModal_UserSwitch,
    "./islands/Navbar/utils.ts": $Navbar_utils,
    "./islands/Teams/NewTeam.tsx": $Teams_NewTeam,
    "./islands/Teams/Teams.tsx": $Teams_Teams,
    "./islands/Test.tsx": $Test,
    "./islands/Textbox.tsx": $Textbox,
    "./islands/account/Login.tsx": $account_Login,
    "./islands/account/Register.tsx": $account_Register,
    "./islands/chat/ChatLayout.tsx": $chat_ChatLayout,
    "./islands/chat/ChatResize.tsx": $chat_ChatResize,
    "./islands/chat/ChatsList.tsx": $chat_ChatsList,
    "./islands/chat/attachments/Attachment.tsx": $chat_attachments_Attachment,
    "./islands/chat/attachments/Attachments.tsx": $chat_attachments_Attachments,
    "./islands/chat/attachments/FileList.tsx": $chat_attachments_FileList,
    "./islands/chat/attachments/PreviewFile.tsx": $chat_attachments_PreviewFile,
    "./islands/chat/messages/ChatMessage.tsx": $chat_messages_ChatMessage,
    "./islands/chat/messages/ChatMessages.tsx": $chat_messages_ChatMessages,
    "./islands/chat/messages/ChatSection.tsx": $chat_messages_ChatSection,
    "./islands/contexts/KVProvider.tsx": $contexts_KVProvider,
    "./islands/contexts/UserProvider.tsx": $contexts_UserProvider,
    "./islands/explore/ExploreFilter.tsx": $explore_ExploreFilter,
    "./islands/explore/ProjectDetails.tsx": $explore_ProjectDetails,
    "./islands/explore/Projects/ExploreProjects.tsx":
      $explore_Projects_ExploreProjects,
    "./islands/explore/Projects/ExploreProjectsDetails.tsx":
      $explore_Projects_ExploreProjectsDetails,
    "./islands/explore/Projects/ExploreProjectsList.tsx":
      $explore_Projects_ExploreProjectsList,
    "./islands/profile/edit.tsx": $profile_edit,
    "./islands/profile/layout.tsx": $profile_layout,
    "./islands/profile/profile.tsx": $profile_profile,
    "./islands/projects/NewProject.tsx": $projects_NewProject,
    "./islands/projects/ProjectChatList.tsx": $projects_ProjectChatList,
    "./islands/projects/ProjectMessages.tsx": $projects_ProjectMessages,
    "./islands/projects/ProjectsHeader.tsx": $projects_ProjectsHeader,
    "./islands/projects/ProjectsLayout.tsx": $projects_ProjectsLayout,
    "./islands/projects/ProjectsList.tsx": $projects_ProjectsList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
