export const testMetrics = [
  'Originality',
  'Concept Diversity',
  'Design Innovation',
  'Creative Risk',
  'Peer Review Creativity',
  'Colour Harmony',
  'Brand Palette',
  'Contrast Ratio',
  'Palette Diversity',
  'Colour Emotion',
  'Visual Balance',
  'Whitespace Utilisation',
  'Grid Alignment',
  'Typography Cohesion',
  'Element Density',
  'Design Intuitiveness',
  'Emotional Resonance',
  'Aesthetic Appeal',
  'Message Clarity',
  'Code Readability',
  'Logic Clarity',
  'Naming Consistency',
  'Function Simplicity',
  'Modular Structure',
  'Reusability',
  'Algorithm Efficiency',
  'Error Handling',
  'Testing Coverage',
  'Code Documentation',
  'Architecture Cohesion',
  'Component Decoupling',
  'Scalability',
  'Maintainability',
  'Responsiveness',
  'Accessibility',
  'Security Practices',
  'Version Control Discipline',
  'Build Stability',
  'Deployment Smoothness',
  'Design Integrity',
  'Structural Soundness',
  'Material Efficiency',
  'Manufacturability',
  'Tolerancing Precision',
  'Load Bearing Capacity',
  'Thermal Stability',
  'Energy Efficiency',
  'System Integration',
  'Failure Resistance',
  'Ease of Assembly',
  'Serviceability',
  'Lifecycle Durability',
  'Cost Effectiveness',
  'Safety Compliance',
  'Regulatory Alignment',
  'Innovation Level',
  'Testing Thoroughness',
  'Documentation Quality',
  'Project Scalability',
];

export const testIndustries = [
  'Agriculture',
  'Automotive',
  'Aerospace',
  'Banking',
  'Biotechnology',
  'Chemical',
  'Construction',
  'Consumer Goods',
  'Cybersecurity',
  'Defense',
  'E-commerce',
  'Education',
  'Energy',
  'Entertainment',
  'Environmental Services',
  'Fashion',
  'Finance',
  'Food & Beverage',
  'Forestry',
  'Gaming',
  'Healthcare',
  'Hospitality',
  'Information Technology',
  'Insurance',
  'Legal Services',
  'Logistics',
  'Manufacturing',
  'Marine',
  'Media & Broadcasting',
  'Mining',
  'Nanotechnology',
  'Oil & Gas',
  'Pharmaceutical',
  'Publishing',
  'Real Estate',
  'Renewable Energy',
  'Retail',
  'Robotics',
  'Space Exploration',
  'Sports',
  'Telecommunications',
  'Tourism',
  'Transportation',
  'Utilities',
  'Venture Capital',
  'Waste Management',
  'Wholesale',
  'Wildlife Conservation',
];

export const testLanguages = [
  'Albanian',
  'Amharic',
  'Arabic',
  'Armenian',
  'Aymara',
  'Azerbaijani',
  'Basque',
  'Bashkir',
  'Bengali',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Catalan',
  'Chewa',
  'Corsican',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Esperanto',
  'Estonian',
  'Fijian',
  'Finnish',
  'French',
  'Frisian',
  'Galician',
  'Georgian',
  'German',
  'Greek',
  'Gujarati',
  'Haitian Creole',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Hungarian',
  'Igbo',
  'Indonesian',
  'Interlingua',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Kazakh',
  'Khmer',
  'Kinyarwanda',
  'Klingon',
  'Korean',
  'Kurdish',
  'Lao',
  'Latvian',
  'Lithuanian',
  'Lojban',
  'Luxembourgish',
  'Macedonian',
  'Maithili',
  'Malagasy',
  'Malay/Indonesian',
  'Malayalam',
  'Mandarin Chinese',
  'Manx',
  'Marathi',
  'Mongolian',
  'Nahuatl',
  'Nepali',
  'Norwegian',
  'Odia',
  'Pashto',
  'Persian (Farsi)',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Quechua',
  'Romanian',
  'Russian',
  'Samoan',
  'Scottish Gaelic',
  'Serbo-Croatian',
  'Sesotho',
  'Sindhi',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Somali',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tagalog',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tigrinya',
  'Tongan',
  'Tswana',
  'Turkish',
  'Turkmen',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Vietnamese',
  'Volapük',
  'Welsh',
  'Wu Chinese (Shanghainese)',
  'Xhosa',
  'Yoruba',
  'Yue Chinese (Cantonese)',
  'Zulu',
];

export const testSkills = [
  'Account Management',
  'Acting',
  'Adaptability',
  'Agile Methodologies',
  'Analytics',
  'Android Development',
  'Animation',
  'Art Direction',
  'Artificial Intelligence',
  'Attention to Detail',
  'Auditing',
  'Automation',
  'Blogging',
  'Bookkeeping',
  'Brand Management',
  'Budgeting',
  'Business Analysis',
  'Business Development',
  'CAD Design',
  'Cloud Computing',
  'Coaching',
  'Communication',
  'Compliance',
  'Conflict Resolution',
  'Content Creation',
  'Copywriting',
  'Critical Thinking',
  'Cryptography',
  'Customer Service',
  'Cybersecurity',
  'Data Analysis',
  'Data Entry',
  'Data Mining',
  'Data Science',
  'Database Administration',
  'Decision Making',
  'Debugging',
  'Design Thinking',
  'Digital Illustration',
  'Digital Marketing',
  'Diplomacy',
  'Drawing',
  'Editing',
  'Electrical Engineering',
  'Electronics',
  'Email Marketing',
  'Emotional Intelligence',
  'Event Planning',
  'Excel (Advanced)',
  'Figma',
  'Finance',
  'Financial Analysis',
  'Financial Planning',
  'First Aid',
  'Front-End Development',
  'Game Design',
  'Graphic Design',
  'Growth Hacking',
  'Hardware Troubleshooting',
  'Illustration',
  'Influencer Marketing',
  'Information Architecture',
  'Instructional Design',
  'Interior Design',
  'iOS Development',
  'IT Support',
  'JavaScript',
  'KPI Tracking',
  'Leadership',
  'Legal Research',
  'Logistics',
  'Machine Learning',
  'Management',
  'Market Research',
  'Marketing Strategy',
  'Mechanical Engineering',
  'Medical Coding',
  'Mentoring',
  'Microsoft Office',
  'Mobile App Design',
  'Negotiation',
  'Network Administration',
  'Notetaking',
  'Object-Oriented Programming',
  'Operations Management',
  'Organisational Skills',
  'Payroll Management',
  'Penetration Testing',
  'People Management',
  'Performance Tuning',
  'Persuasion',
  'Photography',
  'Planning',
  'Podcasting',
  'Policy Development',
  'Presentation Skills',
  'Problem Solving',
  'Product Design',
  'Product Management',
  'Project Management',
  'Proofreading',
  'Public Speaking',
  'Python Programming',
  'Quality Assurance',
  'ReactJS',
  'Research',
  'Risk Management',
  'Robotics',
  'Sales Forecasting',
  'Sales Strategy',
  'Scheduling',
  'Scientific Writing',
  'Scrum',
  'Search Engine Optimisation',
  'Self-Motivation',
  'SEO Auditing',
  'Server Maintenance',
  'Social Media Management',
  'Software Architecture',
  'Software Development',
  'Software Testing',
  'Spreadsheet Modeling',
  'Statistical Analysis',
  'Storytelling',
  'Strategic Thinking',
  'Stress Management',
  'Supply Chain Management',
  'Survey Design',
  'Systems Analysis',
  'Technical Writing',
  'Team Building',
  'Team Management',
  'Technical Support',
  'Telecommunications',
  'Time Management',
  'Trade Skills',
  'Training',
  'Translation',
  'Typing',
  'UI Design',
  'UI/UX Design',
  'Unity Development',
  'User Research',
  'UX Writing',
  'Video Editing',
  'Video Production',
  'Virtual Assistance',
  'Visual Communication',
  'Voiceover',
  'Web Design',
  'Web Development',
  'Wireframing',
  'WordPress',
  'Writing',
];
